// <auto-generated />
namespace Inlamning.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class produktasus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(produktasus));
        
        string IMigrationMetadata.Id
        {
            get { return "201801211843066_produktasus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
